service: serverless-multi-lando
provider:
  name: aws
  runtime: python3.6
  memorySize: 128
plugins:
  - serverless-rust
custom:
  rust:
    cargoFlags: '--features lando/python3-sys'
package:
  individually: true
  exclude:
    - ./**
functions:
  hello:
    handler: liblambda.hello
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/hello/{name}'
          method: GET
          request:
            parameters:
              paths:
                name: true
  goodbye:
    handler: liblambda.goodbye
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/goodbye/{name}'
          method: GET
          request:
            parameters:
              paths:
                name: true
